FROM nsight-compute:12.4.1

RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo'root:password' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#Port 22/Port 2222/' /etc/ssh/sshd_config

EXPOSE 2222

# CMD ["/usr/sbin/sshd", "-D"]

# docker build -f Dockerfile.ssh-server -t sshimg-ncu .
# docker run --rm -it --gpus all --net=host sshimg-ncu # -p 2222:2222
# ssh root@localhost -p 2222